name: Test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Test LTS and v12.15 for ensuring support for exports in package.json
        node-version: [v12.15, v16]

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set ignore engines
        run: yarn config set ignore-engines true

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn

      - name: Validate
        if: matrix.node-version == 'v16'
        run: yarn lint

      - name: Run tests
        run: yarn test:cover --ci

      - name: Check prettier
        run: yarn prettier:check

      - name: Bundle size
        run: |
          GITHUB_RUN_NUMBER_TMP=GITHUB_RUN_NUMBER && export GITHUB_RUN_NUMBER=1;
          echo "$GITHUB_RUN_NUMBER"
          yarn bundlesize
          export GITHUB_RUN_NUMBER=GITHUB_RUN_NUMBER_TMP
          echo "$GITHUB_RUN_NUMBER"

      - name: Build source for remainder tests
        run: yarn build

      - name: Run flow types validation
        run: yarn flow-types validate

      - name: Run import test
        run: yarn test:imports

      - name: Run parcel tests
        run: yarn test:parcel
